###########
## THEME ##
###########

BLACK="#222222"
DARK_BACKGROUND="#292929"
BACKGROUND="#2d2d2d"
DARK_GREY1="#393939"
DARK_GREY2="#515151"
LIGHT_GREY1="#777777"
LIGHT_GREY2="#b4b7b4"
TEXT="#cccccc"
RED="#ff7f7b"
ORANGE="#ffbf70"
YELLOW="#ffd67c"
GREEN="#beda78"
CYAN="#66cccc"
BLUE="#90bee1"
LIGHT_BLUE="#bed6ff"
PURPLE="#efb3f7"
MAGENTA="#ff93b3"

################
## CHARACTERS ##
################

RIGHT_BAR="🮇"
LEFT_BAR="▎"

############
## TWEAKS ##
############

# NOTE TO SELF: install ncurses-term for below line to work
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:Tc:IT=\E[3m"
set -g xterm-keys on
set -g allow-passthrough on
set -g status-style bg=default
set -g mouse on
set -ga terminal-overrides ",*:rgb"
set -g set-clipboard on
set -g base-index 1
set -g pane-base-index 1
set -g focus-events on
set-window-option -g pane-base-index 1

##############
## KEYBINDS ##
##############

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind h resize-pane -L 5
# bind j resize-pane -D 5
# bind k resize-pane -U 5
# bind l resize-pane -R 5

bind -n m-h run "tmux select-window -p"
bind -n m-l run "tmux select-window -n"
bind -n m-space new-window
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

###############
## STATUSBAR ##
###############

set -g status-interval 1

set-option -g renumber-windows on

set -g window-status-separator ""

# Inactive
set -g window-status-format "#[bg=${DARK_BACKGROUND}] #I:#{=20:window_name}#[fg=${DARK_GREY2}]${RIGHT_BAR}#[default]"

# Current
set -g window-status-current-format "\
#[fg=${TEXT},bg=${DARK_GREY1}]\
 \
#[fg=${ORANGE},bg=${DARK_GREY1}]\
#I\
#[fg=${TEXT},bg=${DARK_GREY1}]\
:\
#{=20:window_name}\
#[fg=${GREEN},bg=${DARK_GREY1}]\
${RIGHT_BAR}\
#[default]\
"
set -g window-status-current-style "bold"

# Activity
set -g window-status-activity-style "fg=${YELLOW},bold"

# Bell
set -g window-status-bell-style "fg=${RED},bold"

# Left Status
set -g status-left ""

# Right Status
set -g status-right "\
#[fg=${MAGENTA},bg=${DARK_GREY1}]\
${LEFT_BAR}\
#[fg=${TEXT},bg=${DARK_GREY1}]\
#(whoami)@#H \
#[fg=${BLUE},bg=${DARK_GREY1}]\
${LEFT_BAR}\
#[fg=${TEXT},bg=${DARK_GREY1}]\
#S \
#[default]\
"
