###########
## THEME ##
###########

BLACK="#222222"
DARK_BACKGROUND="#292929"
BACKGROUND="#2d2d2d"
DARK_GREY1="#393939"
DARK_GREY2="#515151"
LIGHT_GREY1="#777777"
LIGHT_GREY2="#b4b7b4"
TEXT="#cccccc"
RED="#ff7f7b"
ORANGE="#ffbf70"
YELLOW="#ffd67c"
GREEN="#beda78"
CYAN="#66cccc"
BLUE="#90bee1"
LIGHT_BLUE="#bed6ff"
PURPLE="#efb3f7"
MAGENTA="#ff93b3"

############
## TWEAKS ##
############

# NOTE TO SELF: install ncurses-term for below line to work
set -g default-terminal "tmux-256color"
set -g status-position bottom
set -g xterm-keys on
set -g allow-passthrough on
set -g status-style bg=default
set -g mouse on
set -g set-clipboard on
set -g base-index 1
set -g pane-base-index 1
set -g focus-events on
set -g history-limit 50000
set-window-option -g pane-base-index 1

##############
## KEYBINDS ##
##############

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n m-h run "tmux select-window -p"
bind -n m-l run "tmux select-window -n"
bind -n m-space new-window
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

###################
## WINDOW STATUS ##
###################

set -g status-interval 1
set -g monitor-activity on
set -g activity-action none
set -g renumber-windows on
set -g window-status-separator " "
set -g status-justify centre
set -g status-left-length 50
set -g status-bg "${DARK_GREY1}"

# Current
set -g window-status-current-format "\
#[fg=${TEXT},bg=${DARK_GREY2}]\
 #(~/.config/tmux/scripts/format_path.lua #{pane_current_path}): #(~/.config/tmux/scripts/window_status_icon.lua #{pane_current_command})\
 #{=20:pane_current_command}\
 \
#[default]\
"

# Inactive
set -g window-status-style "fg=${TEXT},bg=${DARK_BACKGROUND}"
set -g window-status-format "\
#[bg=${DARK_GREY1}]\
 #(~/.config/tmux/scripts/format_path.lua #{pane_current_path}): #(~/.config/tmux/scripts/window_status_icon.lua #{pane_current_command})\
 #{=20:pane_current_command}\
 \
#[default]\
"

# Activity
set -g window-status-activity-style "fg=${YELLOW},bg=${DARK_BACKGROUND},bold"

# Error(?)
set -g window-status-bell-style "fg=${RED},bg=${DARK_BACKGROUND},bold"

###############
## STATUSBAR ##
###############

# Left Status
set -g status-left "\
#[fg=${TEXT},bg=${DARK_GREY2}]\
  \
%I:%M %p \
#[default]\
"

# Right Status
set -g status-right "\
#[fg=${TEXT},bg=${DARK_GREY2}]\
 \
 \
#(whoami)@#H \
 \
#S \
#[default]\
"
