format = """
$sudo\
$directory\
$character\
"""
# [▍]\
# (fg:overlay_bg2)\

right_format = """
$cmd_duration\
$jobs\
$git_branch\
$git_status
$status\
"""

add_newline = false

# [🮈]\
# (fg:overlay_bg2)\
# """

palette = "decaf"

[palettes.decaf]
prompt_fg = '#eeeeee'
text_fg = '#cccccc' # fg for more important elements, too dim to use on prompt itself
background = '#2d2d2d'
# OVERLAYS (background color of elements that are slightly lighter than terminal bg)
overlay_bg1 = '#282828'
overlay_bg2 = '#2a2a2a'
overlay_fg1 = '#777777'
overlay_fg2 = '#515151'
# generic colors
red = '#ff7f7b' # generally used for errors
orange = '#ffbf70'
yellow = '#ffd67c'
green = '#beda78'
blue = '#90bee1'
purple = '#efb3f7'

### LEFT PROMPT

[sudo]
symbol = 's'
style = 'fg:yellow'
format = '[\[$symbol\] ]($style)'
disabled = true

# NOTE: currently unused
[os]
style = 'fg:prompt_fg'
format = '[$symbol ]($style)'
disabled = false

[os.symbols]
Fedora = ''
Void = ''

[directory]
style = 'fg:green'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
fish_style_pwd_dir_length = 3

### RIGHT PROMPT

[cmd_duration]
style = 'fg:overlay_fg1'
format = '[$duration]($style)'
# min_time = 0
# show_milliseconds = true

[jobs]
number_threshold = 1
symbol = ''
style = 'fg:orange'
format = '[ $symbol $number]($style)'

[git_branch]
symbol = '@'
style = 'fg:prompt_fg'
format = '[ $symbol$branch]($style)'

[git_status]
# style = 'bg:background'
modified = '[󰇂 ](fg:yellow)'
deleted = '[󰍴](fg:red)'
stashed = '[󰏗 ](fg:orange)'
untracked = '[?](fg:green)'
renamed = '[󰑕](fg:orange)'
staged = '[](fg:blue)'
# no space, attach it to the `git_branch` module
format = '(\[$all_status\])'

[fill]
symbol = '▁'
style = 'fg:overlay_bg1'

[status]
style = 'red'
format = ' [\[($status)(, $common_meaning)\]]($style)'
disabled = false

[shell]
style = 'fg:purple'
format = '[ $indicator]($style)'
# bash_indicator tends to not work for some reason :c
bash_indicator = ' ' # NOTE: only works with ble.sh framework installed
fish_indicator = ' '
zsh_indicator = '%_'
unknown_indicator = '?'
disabled = true # NOTE: currently disabled and unused

# toml will not calm down unless this part is put last
[character]
format = '$symbol '
success_symbol = ">"
error_symbol = "[>](red)"
