format = """
$sudo\
$directory\
$character\
"""
# [▍](fg:dark_grey_2)\

right_format = """
$cmd_duration\
$jobs\
$git_branch\
$git_status
$status\
[🮈](fg:dark_grey_2)\
"""

add_newline = false
palette = "decaf"

[palettes.decaf]
black = '#222222'
dark_background = '#292929'
background = '#2d2d2d'
dark_grey_1='#393939'
dark_grey_2='#515151'
light_grey_1='#777777'
light_grey_2='#b4b7b4'
text = '#cccccc'
prompt_text = '#eeeeee'
red = '#ff7f7b'
orange = '#ffbf70'
yellow = '#ffd67c'
green = '#beda78'
cyan = '#bed6ff'
blue = '#90bee1'
purple = '#efb3f7'
magenta = '#ff93b3'

### LEFT PROMPT

[sudo]
symbol = 's'
style = 'fg:yellow'
format = '[\[$symbol\] ]($style)'
disabled = true

[os]
style = 'fg:prompt_text'
format = '[$symbol ]($style)'
disabled = false

[os.symbols]
Fedora = ''
Void = ''

[directory]
style = 'fg:green bold'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
fish_style_pwd_dir_length = 3

### RIGHT PROMPT

[cmd_duration]
style = 'fg:light_grey_1'
format = '[$duration]($style)'
# min_time = 0
# show_milliseconds = true

[jobs]
number_threshold = 1
symbol = ''
style = 'fg:orange'
format = '[ $symbol $number]($style)'

[git_branch]
symbol = '@'
style = 'fg:prompt_text'
format = '[ $symbol$branch]($style)'

[git_status]
# style = 'bg:background'
modified = '[󰇂](fg:yellow)'
deleted = '[󰍴](fg:red)'
stashed = '[󰏗](fg:orange)'
untracked = '[?](fg:green)'
renamed = '[󰑕](fg:orange)'
staged = '[󰢪](fg:green)'
# no space, attach it to the `git_branch` module
format = '(\[$all_status\])'

[fill]
symbol = '▁'
style = 'fg:dark_background'

[status]
style = 'red'
format = ' [\[($status)(, $common_meaning)\]]($style)'
disabled = false

[shell]
style = 'fg:purple'
format = '[ $indicator]($style)'
# bash_indicator tends to not work for some reason :c
bash_indicator = ' '
fish_indicator = ' '
zsh_indicator = '%_'
unknown_indicator = '?'
disabled = true

# toml will not calm down unless this part is put last
[character]
format = '$symbol '
success_symbol = ">"
error_symbol = "[>](red)"
